
export const KV_STORE_SCHEMA = {
  'chat.suggestionsEnabled':    'boolean',
  'chat.lastModel':             'string',
  'rag.docsEmbedded':           'boolean',
  'rag.defaultIngestPolicy':    'string',
  'system.updateAvailable':     'boolean',
  'system.latestVersion':       'string',
  'system.earlyAccess':         'boolean',
  'autoUpdate.enabled':         'boolean',
  'autoUpdate.windowStart':     'string',
  'autoUpdate.windowEnd':       'string',
  'autoUpdate.cooloffHours':    'string',
  'autoUpdate.lastAttemptAt':   'string',
  'autoUpdate.lastError':       'string',
  'autoUpdate.lastResult':      'string',
  'autoUpdate.consecutiveFailures': 'string',
  'autoUpdate.autoDisabledReason':  'string',
  'appAutoUpdate.enabled':          'boolean',
  'appAutoUpdate.lastAttemptAt':    'string',
  'appAutoUpdate.lastResult':       'string',
  'contentAutoUpdate.enabled':           'boolean',
  'contentAutoUpdate.windowStart':       'string',
  'contentAutoUpdate.windowEnd':         'string',
  'contentAutoUpdate.cooloffHours':      'string',
  'contentAutoUpdate.maxBytesPerWindow': 'string',
  'contentAutoUpdate.lastAttemptAt':     'string',
  'contentAutoUpdate.lastResult':        'string',
  'contentAutoUpdate.lastError':         'string',
  'contentAutoUpdate.consecutiveFailures': 'string',
  'contentAutoUpdate.autoDisabledReason':  'string',
  'contentAutoUpdate.windowBytesUsed':   'string',
  'contentAutoUpdate.windowResetAt':     'string',
  'ui.hasVisitedEasySetup':     'boolean',
  'ui.theme':                   'string',
  'ai.assistantCustomName':     'string',
  'gpu.type':                   'string',
  'ai.remoteOllamaUrl':         'string',
  'ai.ollamaFlashAttention':    'boolean',
  'ai.amdGpuAcceleration':      'boolean',
  'ai.amdHsaOverride':          'string',
  'ai.autoFixGpuPassthrough':   'boolean',
  'gpu.autoRemediatedAt':       'string',
} as const

type KVTagToType<T extends string> = T extends 'boolean' ? boolean : string

export type KVStoreKey = keyof typeof KV_STORE_SCHEMA
export type KVStoreValue<K extends KVStoreKey> = KVTagToType<(typeof KV_STORE_SCHEMA)[K]>
